### ISSUE TITLE
`usages` crashes Waratah

### ISSUE THREAD

**Issue by reinderien** [microsoft/hidtools#14]
This piece of TOML.:

```toml
            [[applicationCollection.inputReport.logicalCollection.arrayItem]]
            usages = ['Auxiliary Display', 'Stat Not Ready', 'Stat Ready', 'Err Not a loadable character']
```

gets past the parser, and then crashes with

```none
Unable to cast object of type 'System.String' to type 'System.Object[]'.
```

This occurs on Waratah 1.3.0.0. Of course the above syntax is invalid, but ideally a better error message should be generated.
